# Generated by Django 4.2.5 on 2023-09-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
