# Generated by Django 4.2.5 on 2023-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exprience',
            field=models.BooleanField(null=True),
        ),
    ]
