# Generated by Django 4.2.5 on 2023-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_candidate_exprience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
