# Generated by Django 4.2.5 on 2023-09-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_candidate_options_candidate_company_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candiate_email', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('chat', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
